---
galaxy_info:
  author: drew138
  description: installs the aws cli
  license: MIT
  min_ansible_version: 2.16.1
  role_name: aws
  namespace: drew138
  platforms:
    - name: MacOSX
      versions:
        - all
dependencies: []
