---
galaxy_info:
  author: drew138
  description: installs the aerospace window manager
  license: MIT
  min_ansible_version: 2.16.1
  role_name: aerospace
  namespace: drew138
  platforms:
    - name: MacOSX
      versions:
        - all
