---
casks_applications:
  - name: slack
    app: Slack
  - name: discord
    app: Discord
  - name: postman
    app: Postman
  - name: obs
    app: OBS
  - name: bitwarden
    app: Bitwarden
  - name: notion
    app: Notion
  - name: notion-calendar
    app: Notion Calendar
  - name: whatsapp
    app: WhatsApp
  - name: google-chrome
    app: Google Chrome
  - name: utm
    app: UTM
