---
- name: Ensure FelixKratz Homebrew tap is available
  community.general.homebrew_tap:
    name: FelixKratz/formulae
    state: present

- name: Install jankyborders
  community.general.homebrew:
    name:
      - borders
    state: latest
  notify: start_borders_service

- name: Ensure jankyborders config directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - .config
    - .config/borders

- name: Create jankyborders symlink
  ansible.builtin.file:
    src: "{{ ansible_facts['env']['HOME'] }}/.dotfiles/roles/borders/files/bordersrc"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/borders/bordersrc"
    owner: "{{ ansible_facts['env']['USER'] }}"
    state: link
    force: true
    follow: false
