---
galaxy_info:
  author: drew138
  description: installs the rust programming language
  license: MIT
  min_ansible_version: 2.16.1
  role_name: rust
  namespace: drew138
  platforms:
    - name: MacOSX
      versions:
        - all
dependencies:
  - role: zsh
