---
galaxy_info:
  author: drew138
  description: changes wallpaper
  license: MIT
  min_ansible_version: 2.16.1
  role_name: wallpaper
  namespace: drew138
  platforms:
    - name: MacOSX
      versions:
        - all
dependencies:
  - role: repositories
