---
- name: check for starship command
  command: command -v starship >/dev/null 2>&1
  register: installed
  no_log: true
  ignore_errors: true

- name: download starship installer
  get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship-installer.sh
    mode: "u+rwx"
  when: installed.rc != 0
  register: download

- name: run the install script
  shell: /tmp/starship-installer.sh
  when: download.changed

- name: remove starship-installer.sh
  file:
    path: /tmp/starship-installer.sh
    state: absent

- name: create starship symlink
  file:
    src: "{{ user_home }}/.dotfiles/.config/starship.toml"
    dest: "{{ user_home }}/.config/starship.toml"
    owner: "{{ host_user }}"
    state: link
    force: true
