- name: Check Installation
  become_user: "{{ ansible_env.SUDO_USER }}"
  stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh_file

- name: Download OhMyZsh Installer
  get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh_install.sh
    mode: '0755'
    force: 'yes'
  tags:
    - ohmyzsh
  when: not ohmyzsh_file.stat.exists

- name: Install OhMyZsh
  become_user: "{{ ansible_env.SUDO_USER }}"
  command: /tmp/ohmyzsh_install.sh
  when: not ohmyzsh_file.stat.exists

- name: Download Syntax Highlighting Plugin
  become_user: "{{ ansible_env.SUDO_USER }}"
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    clone: yes
    update: yes

- name: Download Auto Suggestions Plugin
  become_user: "{{ ansible_env.SUDO_USER }}"
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    clone: yes
    update: yes

- name: Change Default Shell
  become_user: "{{ ansible_env.SUDO_USER }}"
  shell: 'sudo chsh $USER -s $(which zsh)'

