---
- name: install aerospace
  community.general.homebrew_cask:
    name: nikitabobko/tap/aerospace
    state: present

- name: create ~/.config/aerospace directory
  file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config/aerospace"
    state: directory
    mode: "0700"
    owner: "{{ ansible_facts['env']['USER'] }}"

- name: create aerospace symlink
  file:
    src: "{{ ansible_facts['env']['HOME'] }}/.dotfiles/roles/aerospace/files/aerospace.toml"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/aerospace/aerospace.toml"
    owner: "{{ ansible_facts['env']['USER'] }}"
    state: link
    force: true
    follow: false
