---
- name: install aerospace
  become_user: "{{ ansible_env.USER }}"
  homebrew_cask:
    name: nikitabobko/tap/aerospace
    state: present

- name: create ~/.config/aerospace directory
  become: true
  file:
    path: "{{ ansible_env.HOME }}/.config/aerospace"
    state: directory
    mode: "0700"
    owner: "{{ ansible_env.USER }}"

- name: create aerospace symlink
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/roles/aerospace/files/aerospace.toml"
    dest: "{{ ansible_env.HOME }}/.config/aerospace/aerospace.toml"
    owner: "{{ ansible_env.USER }}"
    state: link
    force: true
    follow: false
