---
- name: install zsh
  become: true
  apt:
    name:
      - zsh
    state: latest

- name: create .workrc.zsh file
  copy:
    content: "#!/bin/bash"
    dest: "{{ ansible_env.HOME }}/.workrc.zsh"
    force: false
    mode: "u+rwx"
    owner: "{{ ansible_env.USER }}"

- name: set user to change shell
  set_fact:
    zsh_user: "{{ ansible_env.USER }}"

- name: change default shell
  become: true
  shell: "sudo chsh {{ zsh_user }} -s $(which zsh)"
  changed_when: false

- name: create .zshrc symlink
  file:
    src: "{{ ansible_env.HOME }}/.dotfiles/roles/zsh/files/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
    force: true
