---
- name: install zsh
  become: true
  become_user: "{{ ansible_facts['env']['USER'] }}"
  community.general.homebrew:
    name:
      - zsh
    state: latest

- name: create .work.zsh file
  copy:
    content: "#!/bin/bash"
    dest: "{{ ansible_facts['env']['HOME'] }}/.work.zsh"
    force: false
    mode: "0700"
    owner: "{{ ansible_facts['env']['USER'] }}"

- name: set user to change shell
  set_fact:
    zsh_user: "{{ ansible_facts['env']['USER'] }}"

- name: change default shell
  become: true
  shell: "chsh -s $(which zsh) {{ zsh_user }}"
  changed_when: false

- name: create .zshrc symlink
  ansible.builtin.file:
    src: "{{ ansible_facts['env']['HOME'] }}/.dotfiles/roles/zsh/files/.zshrc"
    dest: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
    state: link
    force: true
    follow: false
