[format]
  [format.rules]
    array-bracket-space-width         = 0
    array-comma-space-width           = 1
    date-time-delimiter               = "T"
    indent-style                      = "space"
    indent-sub-tables                 = true
    indent-table-key-value-pairs      = true
    indent-width                      = 2
    inline-table-brace-space-width    = 1
    inline-table-comma-space-width    = 1
    key-value-equals-sign-alignment   = true
    key-value-equals-sign-space-width = 1
    line-ending                       = "lf"
    line-width                        = 80
    string-quote-style                = "double"
    trailing-comment-alignment        = false
    trailing-comment-space-width      = 2
