---
galaxy_info:
  author: drew138
  description: sets up ssh configs
  license: MIT
  min_ansible_version: 2.16.1
  role_name: ssh
  namespace: drew138
  platforms:
    - name: MacOSX
      versions:
        - all
dependencies: []
