---
- name: set request headers
  set_fact:
    request_headers: >-
      {{
        {
          'Accept': 'application/vnd.github.v3+json'
        } | combine(
          {
            'Authorization': 'token ' + lookup('env','GHUB_ACCESS_TOKEN')
          } if (lookup('env', 'GHUB_ACCESS_TOKEN') | length) > 0 else {}
        )
      }}

- name: fetch latest release data
  uri:
    url: "https://api.github.com/repos/Homebrew/brew/releases/latest"
    method: GET
    return_content: true
    headers: "{{ request_headers }}"
  register: release_data

- name: extract url for Homebrew.pkg
  set_fact:
    pkg_url: "{{ release_data.json['assets'] | selectattr('name', 'search', '.pkg') | map(attribute='browser_download_url') | first }}"

- name: download Homebrew.pkg
  ansible.builtin.get_url:
    url: "{{ pkg_url }}"
    dest: /tmp/Homebrew.pkg
    mode: '0644'
  changed_when: false

- name: install Homebrew.pkg
  become: true
  ansible.builtin.command:
    cmd: "installer -pkg /tmp/Homebrew.pkg -target /"
  changed_when: false

- name: Clean up .pkg file
  ansible.builtin.file:
    path: /tmp/Homebrew.pkg
    state: absent
  changed_when: false
