---
- name: Install wezterm
  community.general.homebrew_cask:
    name:
      - wezterm
    state: present
  ignore_errors: true

- name: Create .wezterm.lua symlink
  ansible.builtin.file:
    src: "{{ ansible_facts['env']['HOME'] }}/.dotfiles/roles/wezterm/files/.wezterm.lua"
    dest: "{{ ansible_facts['env']['HOME'] }}/.wezterm.lua"
    owner: "{{ ansible_facts['env']['USER'] }}"
    state: link
    force: true
    follow: false
