---
- name: install wezterm
  become_user: "{{ ansible_facts['env']['USER'] }}"
  community.general.homebrew_cask:
    name:
      - wezterm
    state: present
  ignore_errors: true

- name: create .wezterm.lua symlink
  file:
    src: "{{ ansible_facts['env']['HOME'] }}/.dotfiles/roles/wezterm/files/.wezterm.lua"
    dest: "{{ ansible_facts['env']['HOME'] }}/.wezterm.lua"
    owner: "{{ ansible_facts['env']['USER'] }}"
    state: link
    force: true
    follow: false
