---
- name: Enable tap to click (user domain)
  ansible.builtin.command: defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
  changed_when: false

- name: Enable tap to click (trackpad driver)
  ansible.builtin.command: defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
  changed_when: false
