---
- name: Install homebrew casks
  ansible.builtin.include_tasks: install_cask.yml
  loop_control:
    loop_var: cask
    extended: true
    extended_allitems: false
  loop: "{{ casks_applications }}"
