---
- name: Ensure hashicorp Homebrew tap is available
  community.general.homebrew_tap:
    name: hashicorp/tap
    state: present

- name: Install terraform
  community.general.homebrew:
    name:
      - hashicorp/tap/terraform
    state: latest
