---
- name: change keyboard repeat rates
  ansible.builtin.shell: "{{ keyboard_setup_command }}"
  args:
    executable: /bin/bash
  changed_when: false
  loop:
    - defaults write -g InitialKeyRepeat -int 15
    - defaults write -g KeyRepeat -int 2
  loop_control:
    loop_var: keyboard_setup_command
