---
galaxy_info:
  author: drew138
  description: installs the go programming language
  license: MIT
  min_ansible_version: 2.16.1
  role_name: go
  namespace: drew138
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: MacOSX
      versions:
        - all
dependencies: []
