---
- name: Ensure FelixKratz Homebrew tap is available
  community.general.homebrew_tap:
    name: FelixKratz/formulae
    state: present

- name: Install sketchybar
  community.general.homebrew:
    name:
      - sketchybar
    state: latest
  notify: start_sketchybar_service

- name: Ensure sketchybar config directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config/sketchybar"
    state: directory
    mode: "0755"

- name: Create sketchybar symlink
  ansible.builtin.file:
    src: "{{ ansible_facts['env']['HOME'] }}/.dotfiles/roles/sketchybar/files"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/sketchybar"
    owner: "{{ ansible_facts['env']['USER'] }}"
    state: link
    force: true
    follow: false
