---
galaxy_info:
  author: drew138
  description: installs various clis
  license: MIT
  min_ansible_version: 2.16.1
  role_name: cli
  namespace: drew138
  platforms:
    - name: MacOSX
      versions:
        - all
dependencies:
  - role: homebrew
  - role: zsh
