---
- name: Verify
  hosts: localhost
  vars_files:
    - ../../vars/main.yml
  tasks:
    - name: Check if the cargo directory exists
      stat:
        path: "{{ rust_host_user }}/.cargo"
      register: cargo_directory_facts

    - name: Fail if cargo directory does not exist
      fail:
        msg: "directory {{ rust_host_user }}/.cargo does not exist."
      when: not cargo_directory_facts.stat.exists

    - name: Check if the cargo binary exists
      stat:
        path: "{{ rust_host_user }}/.cargo/bin/cargo"
      register: cargo_binary_facts

    - name: Fail if cargo binary does not exist
      fail:
        msg: "rustc binary does not exist."
      when: not cargo_binary_facts.stat.exists

    - name: Check if the rustc binary exists
      stat:
        path: "{{ rust_host_user }}/.cargo/bin/rustc"
      register: rustc_binary_facts

    - name: Fail if rustc binary does not exist
      fail:
        msg: "rustc binary does not exist."
      when: not rustc_binary_facts.stat.exists
