---
scripts_symlinks:
  - src: "{{ ansible_facts.env.HOME }}/.dotfiles/roles/scripts/files/conventional_commit.sh"
    dest: "/usr/local/bin/commit"
  # - src: "{{ ansible_facts.env.HOME }}/.dotfiles/roles/scripts/files/nvim_dir.sh"
  #   dest: "/usr/local/bin/nd"
  # - src: "{{ ansible_facts.env.HOME }}/.dotfiles/roles/scripts/files/nvim_file.sh"
  #   dest: "/usr/local/bin/nf"
  - src: "{{ ansible_facts.env.HOME }}/.dotfiles/roles/scripts/files/repo.sh"
    dest: "/usr/local/bin/repo"
