---
galaxy_info:
  author: drew138
  description: installs zsh
  license: MIT
  min_ansible_version: 2.16.1
  role_name: zsh
  namespace: drew138
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: MacOSX
      versions:
        - all
dependencies:
  - role: starship
  - role: repositories
  - role: nerdfonts
