---
- name: Change appearance to darkmode
  ansible.builtin.shell: osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to true'
  args:
    executable: /bin/bash
  changed_when: false
