---
- name: disable system error beep
  command: >
    defaults write NSGlobalDomain com.apple.sound.beep.feedback -bool false
  changed_when: false

- name: mute startup chime
  command: >
    nvram StartupMute=%01
  become: true
  changed_when: false
