---
- name: Disable system error beep
  ansible.builtin.command: >
    defaults write NSGlobalDomain com.apple.sound.beep.feedback -bool false
  changed_when: false

- name: Mute startup chime
  ansible.builtin.command: >
    nvram StartupMute=%01
  become: true
  changed_when: false
