---
- name: installs cmake
  become: true
  become_user: "{{ ansible_facts['env']['USER'] }}"
  community.general.homebrew_cask:
    name:
      - cmake
    state: present
  ignore_errors: true

- name: install dependencies
  become: true
  become_user: "{{ ansible_facts['env']['USER'] }}"
  community.general.homebrew:
    name:
      - xclip
      - make
      - python
    state: latest

- name: check if nvim is installed
  ansible.builtin.stat:
    path: /usr/local/bin/nvim
  register: nvim_is_installed
  changed_when: not nvim_is_installed.stat.exists
  notify:
    - install_neovim_development_tools

- name: clone nvim repository
  become: true
  become_user: "{{ ansible_facts['env']['USER'] }}"
  git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ ansible_facts['env']['HOME'] }}/dev/neovim"
    version: "{{ nvim_release_branch }}"
    depth: 1
    clone: true
    update: true
    force: true

- name: build and install nvim
  become: true
  ansible.builtin.shell:
    cmd: |
      sudo make distclean
      sudo make CMAKE_BUILD_TYPE=RelWithDebInfo
      sudo make install
    chdir: "{{ ansible_facts['env']['HOME'] }}/dev/neovim"
  changed_when: false
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_facts['env']['PATH'] }}"

- name: ensure virtual environment is created
  ansible.builtin.command: python3 -m venv "{{ ansible_facts['env']['HOME'] }}/.nvimvenv"
  args:
    creates: "{{ ansible_facts['env']['HOME'] }}/.nvimvenv/bin/activate"
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_facts['env']['PATH'] }}"

- name: install pynvim in virtual environment
  pip:
    name: pynvim
    state: latest
    virtualenv: "{{ ansible_facts['env']['HOME'] }}/.nvimvenv"
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_facts['env']['PATH'] }}"

- name: install global npm packages required by neovim
  ansible.builtin.shell: "source {{ ansible_facts['env']['HOME'] }}/.nvm/nvm.sh && npm install -g {{ npm_package }}"
  args:
    executable: /bin/bash
  loop:
    - "tree-sitter-cli"
    - "neovim"
  loop_control:
    loop_var: npm_package
  changed_when: false

- name: install luajit
  become: true
  become_user: "{{ ansible_facts['env']['USER'] }}"
  community.general.homebrew:
    name:
      - luajit
    state: latest

- name: create ~/.config directory
  become: true
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config"
    state: directory
    mode: "0755"
    owner: "{{ ansible_facts['env']['USER'] }}"

- name: create nvim symlink
  ansible.builtin.file:
    src: "{{ ansible_facts['env']['HOME'] }}/.dotfiles/roles/nvim/files"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/nvim"
    owner: "{{ ansible_facts['env']['USER'] }}"
    state: link
    force: true
    follow: false
